// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const String _webApiKey = String.fromEnvironment('WEB_API_KEY');

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform is not used on Android. '
          'Use Firebase.initializeApp() without options (google-services.json).',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform is not used on iOS. '
          'Use Firebase.initializeApp() without options (GoogleService-Info.plist).',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for Web in this project.',
        );
    }
  }

  /// Web Firebase options (obligatoire)
  static FirebaseOptions get web {
    _assertKeyProvided(_webApiKey, 'WEB_API_KEY');
    return const FirebaseOptions(
      apiKey: _webApiKey,
      appId: '1:65125955362:web:93925971802530172d577b',
      messagingSenderId: '65125955362',
      projectId: 'recette-magique-7de15',
      authDomain: 'recette-magique-7de15.firebaseapp.com',
      storageBucket: 'recette-magique-7de15.firebasestorage.app',
      measurementId: 'G-Q7G11YSZC5',
    );
  }
}

void _assertKeyProvided(String value, String name) {
  if (value.isEmpty) {
    throw StateError(
      'Missing $name. Build/run the web app with: --dart-define=$name=YOUR_VALUE',
    );
  }
}
