// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB18m6Uk28iUwrDkPzdkqlWnR5t1HmGJhc',
    appId: '1:65125955362:web:93925971802530172d577b',
    messagingSenderId: '65125955362',
    projectId: 'recette-magique-7de15',
    authDomain: 'recette-magique-7de15.firebaseapp.com',
    storageBucket: 'recette-magique-7de15.firebasestorage.app',
    measurementId: 'G-Q7G11YSZC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY20OE3o_CPXpkMdlIBjuV3a-C6RcMJwg',
    appId: '1:65125955362:android:a568a6e324e439cf2d577b',
    messagingSenderId: '65125955362',
    projectId: 'recette-magique-7de15',
    storageBucket: 'recette-magique-7de15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfjRMhjYDLsmz4a_TwNEVCnCejaYXMO0A',
    appId: '1:65125955362:ios:1c2fc1c5c3c9ae6b2d577b',
    messagingSenderId: '65125955362',
    projectId: 'recette-magique-7de15',
    storageBucket: 'recette-magique-7de15.firebasestorage.app',
    iosBundleId: 'com.mycompany.Counterapp1',
  );
}
